// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";
// import Link from "next/link";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({ children }) {
//   return (
//     <html
//       lang="en"
//       className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
//     >
//       <body className="min-h-full flex flex-col">
//         <Link href="/courses">Courses</Link>
//         <Link href="/setting">Setting</Link>
//         <Link href="/student">Student</Link>
//         {children}
//       </body>
//     </html>
//   );
// }




import './globals.css';
import Link from 'next/link';

export default function RootLayout({ children }) {
  return (
    <html>
      <body>

        <nav className="navbar">
          {/* <Link href="/">Home</Link> */}
          <Link href="/courses">Courses</Link>
          <Link href="/setting">Setting</Link>
          <Link href="/student">Student</Link>
        </nav>

        <div className="container">
          {children}
        </div>

      </body>
    </html>
  );
}